glib2/branches/glib2-2-36: Update to version 2.36.3, compiles on i386, fixed tests for i386

diff --git a/csw/mgar/pkg/glib2/branches/glib2-2-36/files/0022-Change-shell-to-bash-in-test-shell-scripts.patch b/csw/mgar/pkg/glib2/branches/glib2-2-36/files/0022-Change-shell-to-bash-in-test-shell-scripts.patch
--- a/csw/mgar/pkg/glib2/branches/glib2-2-36/files/0022-Change-shell-to-bash-in-test-shell-scripts.patch
+++ b/csw/mgar/pkg/glib2/branches/glib2-2-36/files/0022-Change-shell-to-bash-in-test-shell-scripts.patch
@@ -1,6 +1,6 @@
-From f7e0a1ff2fba2b57c61d24a41ff6a18cf63eeda0 Mon Sep 17 00:00:00 2001
-From: Rafael Ostertag <raos@opencsw.org>
-Date: Mon, 27 Aug 2012 00:47:58 +0200
+From ebf6b06ed4aabe24425b09bd145c0191c431aa7d Mon Sep 17 00:00:00 2001
+From: Ralph Boehme <sloowfranklin@gmail.com>
+Date: Sat, 29 Jun 2013 08:28:38 +0200
 Subject: [PATCH] Change shell to bash in test shell scripts
 
 ---
@@ -9,7 +9,7 @@ Subject: [PATCH] Change shell to bash in test shell scripts
  2 files changed, 10 insertions(+), 4 deletions(-)
 
 diff --git a/tests/run-assert-msg-test.sh b/tests/run-assert-msg-test.sh
-index b6045d6..c50cc09 100755
+index 58305b0..2c162bc 100755
 --- a/tests/run-assert-msg-test.sh
 +++ b/tests/run-assert-msg-test.sh
 @@ -1,4 +1,10 @@
@@ -24,7 +24,7 @@ index b6045d6..c50cc09 100755
  
  fail ()
  {
-@@ -21,7 +27,7 @@ fi
+@@ -29,7 +35,7 @@ fi
  
  echo_v "Running assert-msg-test"
  OUT=$(./assert-msg-test 2>&1) && fail "assert-msg-test should abort"
@@ -33,8 +33,8 @@ index b6045d6..c50cc09 100755
    fail "does not print assertion message"
  
  if ! type gdb >/dev/null 2>&1; then
-@@ -38,7 +44,7 @@ OUT=$(libtool --mode=execute gdb --batch --ex run --ex "set print elements 0" --
-   fail "failed to run gdb"
+@@ -41,7 +47,7 @@ echo_v "Running gdb on assert-msg-test"
+ OUT=$($LIBTOOL --mode=execute gdb --batch -x ${srcdir:-.}/assert-msg-test.gdb ./assert-msg-test 2> $error_out) || fail "failed to run gdb"
  
  echo_v "Checking if assert message is in __glib_assert_msg"
 -if ! echo "$OUT" | grep -q '^$1.*"ERROR:.*assert-msg-test.c:.*:.*main.*: assertion failed: (42 < 0)"'; then
@@ -53,5 +53,5 @@ index 24f3d69..9fd1038 100755
  fail ()
  {
 -- 
-1.7.11.3
+1.8.3.1
 
