postgresql/trunk: New upstream release 9.2.0

diff --git a/csw/mgar/pkg/postgresql/trunk/Makefile b/csw/mgar/pkg/postgresql/trunk/Makefile
--- a/csw/mgar/pkg/postgresql/trunk/Makefile
+++ b/csw/mgar/pkg/postgresql/trunk/Makefile
@@ -87,10 +87,10 @@
 # maintainers to use `pg_config'.
 
 NAME = postgresql
-BASE_VERSION = 9.1
+BASE_VERSION = 9.2
 VERSION_NODOT = $(subst .,_,$(BASE_VERSION))
 BASE_VERSION_NODOT = $(subst .,,$(BASE_VERSION))
-PATCHLEVEL = 5
+PATCHLEVEL = 0
 VERSION = $(BASE_VERSION).$(PATCHLEVEL)
 CATEGORIES = apps
 GARTYPE = v2
@@ -126,11 +126,15 @@ PGNAMEVERSIONED		= $(NAME)$(BASE_VERSION_NODOT)
 # This variable has been introduced for using in EXPANDVARS files
 PGNAME_VERSIONED	= $(NAME)-$(BASE_VERSION_NODOT)
 # Those BIN_NAMES_* are used both, for package creation and alternatives.
+#
+# The distinction between server and client binaries is taken from the
+# FreeBSD postgresql port.
+# 
 # 8.4 has removed ipcclean
-BIN_NAMES_SERVER	= initdb pg_controldata pg_ctl pg_resetxlog postmaster postgres
+BIN_NAMES_SERVER	= initdb pg_controldata pg_ctl pg_resetxlog pg_receivexlog pg_basebackup postmaster postgres
 BIN_NAMES_DEVEL		= ecpg pg_config
-BIN_NAMES_CLIENT	= clusterdb createdb createlang createuser dropdb droplang dropuser pg_dump pg_dumpall pg_restore psql reindexdb vacuumdb pg_basebackup clusterdb
-BIN_NAMES_CONTRIB	= oid2name pgbench pg_standby vacuumlo pg_upgrade pg_archivecleanup pg_test_fsync
+BIN_NAMES_CLIENT	= clusterdb createdb createlang createuser dropdb droplang dropuser pg_dump pg_dumpall pg_restore psql reindexdb vacuumdb clusterdb
+BIN_NAMES_CONTRIB	= oid2name pgbench pg_standby vacuumlo pg_upgrade pg_archivecleanup pg_test_fsync pg_test_timing
 # These are shared objects used by the server. Please note, contrib installs
 # also shared object in the same place, so make sure you don't mix up things
 SO_NAMES_SERVER		 = ascii_and_mic.so cyrillic_and_mic.so dict_snowball.so euc_cn_and_mic.so
@@ -155,7 +159,7 @@ SO_NAMES_CONTRIB	+= isn.so lo.so ltree.so moddatetime.so pageinspect.so pg_buffe
 SO_NAMES_CONTRIB	+= pg_freespacemap.so pg_trgm.so pgcrypto.so pgrowlocks.so pgstattuple.so
 SO_NAMES_CONTRIB	+= pgxml.so refint.so seg.so sslinfo.so tablefunc.so test_parser.so timetravel.so tsearch2.so
 SO_NAMES_CONTRIB	+= auto_explain.so btree_gin.so citext.so pg_stat_statements.so unaccent.so dummy_seclabel.so
-SO_NAMES_CONTRIB	+= auth_delay.so file_fdw.so
+SO_NAMES_CONTRIB	+= auth_delay.so file_fdw.so tcn.so
 # Those are the extension provided by contrib.
 #
 # This has been introduced with 9.1
@@ -172,7 +176,7 @@ EXT_NAMES_CONTRIB	+= dict_xsyn--1.0.sql dict_xsyn.control dict_xsyn--unpackaged-
 EXT_NAMES_CONTRIB	+= earthdistance--1.0.sql earthdistance.control earthdistance--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= file_fdw--1.0.sql file_fdw.control 
 EXT_NAMES_CONTRIB	+= fuzzystrmatch--1.0.sql fuzzystrmatch.control fuzzystrmatch--unpackaged--1.0.sql
-EXT_NAMES_CONTRIB	+= hstore--1.0.sql hstore.control hstore--unpackaged--1.0.sql 
+EXT_NAMES_CONTRIB	+= hstore--1.0--1.1.sql hstore--1.1.sql hstore.control hstore--unpackaged--1.0.sql 
 EXT_NAMES_CONTRIB	+= insert_username--1.0.sql insert_username.control insert_username--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= intagg--1.0.sql intagg.control intagg--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= intarray--1.0.sql intarray.control intarray--unpackaged--1.0.sql
@@ -185,7 +189,7 @@ EXT_NAMES_CONTRIB	+= pg_buffercache--1.0.sql pg_buffercache.control pg_buffercac
 EXT_NAMES_CONTRIB	+= pgcrypto--1.0.sql pgcrypto.control pgcrypto--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= pg_freespacemap--1.0.sql pg_freespacemap.control pg_freespacemap--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= pgrowlocks--1.0.sql pgrowlocks.control pgrowlocks--unpackaged--1.0.sql
-EXT_NAMES_CONTRIB	+= pg_stat_statements--1.0.sql pg_stat_statements.control pg_stat_statements--unpackaged--1.0.sql
+EXT_NAMES_CONTRIB	+= pg_stat_statements--1.1.sql pg_stat_statements--1.0--1.1.sql pg_stat_statements.control pg_stat_statements--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= pgstattuple--1.0.sql pgstattuple.control pgstattuple--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= pg_trgm--1.0.sql pg_trgm.control pg_trgm--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= refint--1.0.sql refint.control refint--unpackaged--1.0.sql
@@ -197,6 +201,7 @@ EXT_NAMES_CONTRIB	+= timetravel--1.0.sql timetravel.control timetravel--unpackag
 EXT_NAMES_CONTRIB	+= tsearch2--1.0.sql tsearch2.control tsearch2--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= unaccent--1.0.sql unaccent.control unaccent--unpackaged--1.0.sql
 EXT_NAMES_CONTRIB	+= xml2--1.0.sql xml2.control xml2--unpackaged--1.0.sql
+EXT_NAMES_CONTRIB	+= tcn.control tcn--1.0.sql
 # Miscellaneous files
 MISC_NAMES_SERVER	+= .*/share/$(NAME)/$(BASE_VERSION_NODOT)/conversion_create.sql
 MISC_NAMES_SERVER	+= .*/share/$(NAME)/$(BASE_VERSION_NODOT)/information_schema.sql
@@ -269,13 +274,13 @@ EXPANDVARS += README.CSW
 
 # This patch will replace /usr/local/include by /opt/csw/include in
 # ecpg.c and thus silence a checkpkg error.
-PATCHFILES += 0000-ecpg-usr-local-include-replacement.patch
+PATCHFILES += 0001-ecpg-usr-local-include-replacement.patch
 # Test running on a NFS may fail. Thus we let the test run in
-# /var/tmp/pgsql/tmp_check
-PATCHFILES += 0000-Run-tests-in-var-tmp-pgsql-tmp_check.patch
+# /var/tmp/pgsql92/tmp_check
+PATCHFILES += 0000-Run-tests-in-var-tmp-pgsql92-tmp_check.patch
 # By default, src/makefiles/Makefile.solaris uses -Wl,-R'$(rpathdir)'
 # which isn't properly digested by Sun's ld
-PATCHFILES += 0000-Use-plain-rpath.patch
+PATCHFILES += 0002-Use-plain-rpath.patch
 
 INITSMF = $(sysconfdir)/init\.d/$(INITSCRIPTFILE_VERSIONED)
 USERGROUP = $(USERGROUPDIR)/$(USERGROUPFILE_VERSIONED)
@@ -525,7 +530,13 @@ pre-configure-modulated:
 	@echo " ===> Adjusting pkglibdir in $(WORKSRC)/src/Makefile.global.in"
 	@if [ -r $(WORKSRC)/src/Makefile.global.in ] ; then \
 		gsed -i -r -e 's|^(pkglibdir[[:space:]]*=[[:space:]]*)\$$\(libdir\).*$$|\1$$(libdir)/postgresql/$(BASE_VERSION_NODOT)|' $(WORKSRC)/src/Makefile.global.in ; \
+	else \
+		echo "$(WORKSRC)/src/Makefile.global.in not found. Aborting" ; \
+		exit 1 ; \
 	fi
+	@echo " ===> Setting temp-install dir in $(WORKSRC)/src/Makefile.global.in"
+	gsed -i -r -e 's|\./tmp_check|/var/tmp/pgsql$(BASE_VERSION_NODOT)/tmp_check|g' -e 's|tmp_check/|/var/tmp/pgsql$(BASE_VERSION_NODOT)/tmp_check|g' \
+		$(WORKSRC)/src/Makefile.global.in
 	@$(MAKECOOKIE)
 
 post-build-modulated:
