Adding target that applies a command in each subdir

diff --git a/csw/mgar/pkg/Makefile b/csw/mgar/pkg/Makefile
--- a/csw/mgar/pkg/Makefile
+++ b/csw/mgar/pkg/Makefile
@@ -1,5 +1,26 @@
+# vim: ft=make ts=4 sw=4 noet
+# This makefile is to be included from Makefiles in each category
+# directory.
+
 default:
 	@echo "You are in the pkg/ directory."
+
+%:
+	@for i in $(filter-out CVS/,$(wildcard */)) ; do \
+		$(MAKE) -C $$i $* ; \
+	done
+
+paranoid-%:
+	@for i in $(filter-out CVS/,$(wildcard */)) ; do \
+		$(MAKE) -C $$i $* || exit 2; \
+	done
+
+export BUILDLOG ?= $(shell pwd)/buildlog.txt
+
+report-%:
+	@for i in $(filter-out CVS/,$(wildcard */)) ; do \
+		$(MAKE) -C $$i $* || echo "	*** make $* in $$i failed ***" >> $(BUILDLOG); \
+	done
 
 newpkg-%:
 	@svn mkdir $* $*/tags $*/branches $*/trunk $*/trunk/files
