checkpkg: custom-pkgtrans using bash

diff --git a/csw/mgar/gar/v2/bin/custom-pkgtrans b/csw/mgar/gar/v2/bin/custom-pkgtrans
--- a/csw/mgar/gar/v2/bin/custom-pkgtrans
+++ b/csw/mgar/gar/v2/bin/custom-pkgtrans
@@ -1,9 +1,12 @@
-#!/bin/ksh -p
+#!/bin/bash
 # 
 # $Id$
 #
 # This file exists in order to avoid implementing pipelines in Python.  It
 # could be integrated into the package stats collection program.
+
+set -u
+set -e
 
 command_basename=`basename $0`
 command_basedir="${0%/${command_basename}}"
@@ -12,11 +15,11 @@ readonly command_basename command_basedir libshdir
 . "${libshdir}/libcheckpkg.sh"
 
 if [[ -z "$1" || -z "$2" || -z "$3" ]]; then
-	print >&2 "usage: $0 <file.pkg> <targetdir> <pkgname>"
+	echo >&2 "usage: $0 <file.pkg> <targetdir> <pkgname>"
 	exit 1
 fi
 if [[ "$3" == "all" ]]; then
-  print >&2 "This script can't handle 'all' as the third argument"
+  echo >&2 "This script can't handle 'all' as the third argument"
   exit 1
 fi
 custom_pkgtrans "$1" "$2" "$3"
