ca_certificates: improved certification selection configuration

diff --git a/csw/mgar/pkg/ca_certificates/trunk/files/update-ca-certificates b/csw/mgar/pkg/ca_certificates/trunk/files/update-ca-certificates
--- a/csw/mgar/pkg/ca_certificates/trunk/files/update-ca-certificates
+++ b/csw/mgar/pkg/ca_certificates/trunk/files/update-ca-certificates
@@ -1,7 +1,7 @@
 #!/bin/sh -e
 #
 # update-ca-certificates
-# Debian script adapted for Solaris by Yann Rouillard
+# Script inspired by debian script update-ca-certificates
 #
 # Copyright (c) 2003 Fumitoshi UKAI <ukai@debian.or.jp>
 # Copyright (c) 2008 Yann Rouillard <yann@pleiades.fr.eu.org>
@@ -21,13 +21,59 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
 
-verbose=0
-fresh=0
-while [ $# -gt 0 ];
-do
+CACERTS_CONF=/opt/csw/etc/ca-certificates.conf
+CACERTS_DIR=/opt/csw/share/ca-certificates
+CERTBUNDLE=ca-certificates.crt
+CERTSDIR=/opt/csw/etc/ssl/certs
+
+
+# find the certificate files corresponding to the given pattern
+find_certfile ()
+{
+	if [ -f "$CACERTS_DIR/$1" ]; then
+		echo "$CACERTS_DIR/$1"
+	elif [ -f "$1" ]; then
+		echo "$1"
+	else
+		# if the file doesn't exist we suppose it's a find pattern
+		# like *.crt
+		DIRNAME="`dirname "$1"`"
+		if [ "$DIRNAME" = "." ]; then
+			DIRNAME="$CACERTS_DIR"
+		fi
+		BASENAME="`basename "$1"`"
+		find $DIRNAME -name "$BASENAME" 
+	fi
+}
+
+
+# return the full paths of all certificate files
+get_certfile_list ()
+{
+	# first we find all excluded certificates, excluding duplicates
+	sed -ne '/^ *!/s/^ *! *//p' "$CACERTS_CONF" | while read CERTFILE; do
+		[ -n "$CERTFILE" ] && find_certfile "$CERTFILE"
+	done | sort -u > /tmp/update-ca-certificates.tmp.$$
+
+	# then we find all certificates excluding duplicates
+	# and excluded certificates
+	sed -e '/^ *[#!]/d' "$CACERTS_CONF" | while read CERTFILE; do
+		[ -n "$CERTFILE" ] && find_certfile "$CERTFILE"
+	done | sort -u | {
+		while read CERTFILE; do
+			grep -w "$CERTFILE" /tmp/update-ca-certificates.tmp.$$ >/dev/null || echo "$CERTFILE"
+		done
+	}
+
+	rm -f /tmp/update-ca-certificates.tmp.$$
+}
+
+
+VERBOSE=0
+while [ $# -gt 0 ]; do
 	case $1 in
 		--verbose|-v)
-			verbose=1;;
+			VERBOSE=1;;
 
 		--help|-h|*)
 			echo "$0: [--verbose] [--fresh]"
@@ -36,42 +82,59 @@ do
 	shift
 done
 
-CERTSCONF=/opt/csw/etc/ca-certificates.conf
-CERTSDIR=/opt/csw/share/ca-certificates
-CERTBUNDLE=ca-certificates.crt
-ETCCERTSDIR=/opt/csw/etc/ssl/certs
 
-if [ ! -f "$CERTSCONF" ]; then
-	echo "ERROR: $CERTSCONF doesn't exist !" >&2
+if [ ! -f "$CACERTS_CONF" ]; then
+	echo "ERROR: $CACERTS_CONF doesn't exist !" >&2
 	exit 2
 fi
 
-cd $ETCCERTSDIR
-find . -type l -print | while read SYMLINK; do
-	test -f $SYMLINK || rm -f $SYMLINK
+printf "Updating certificates in $CERTSDIR..."
+
+
+# first we remove the existing symlink
+find "$CERTSDIR" -type l -print | while read SYMLINK; do
+	[ ! -L "$SYMLINK" ] || rm -f "$SYMLINK"
 done
 
-printf "Updating certificates in $ETCCERTSDIR..."
+# then we recreate them
+get_certfile_list | while read CERTFILE; do
+	SYMLINK="`basename "$CERTFILE"`"
+	SYMLINK="`echo $SYMLINK | sed -e 's/\.[^\.]*$//'`.pem"
 
-BUNDLETMP=`mktemp "${CERTBUNDLE}.tmp.XXXXXX"`
-sed -e '/^#/g' "$CERTSCONF" | while read CERTFILE; do
-	if [ ! -f "$CERTFILE" ]; then
-		if [ ! -f "$CERTSDIR/$CERTFILE" ]; then
-			continue
+	cd "$CERTSDIR" && ln -sf "$CERTFILE" "$SYMLINK"
+done
+
+# we create the certificate bundle file which contains all the
+# certificate, some software prefer to use this file 
+# (and this is mandatory for software linked with gnutls)
+cat "$CERTSDIR/"*.pem > "$CERTSDIR/$CERTBUNDLE.tmp" 2>/dev/null || true
+chmod 0644 "$CERTSDIR/$CERTBUNDLE.tmp"
+mv -f "$CERTSDIR/$CERTBUNDLE.tmp" "$CERTSDIR/$CERTBUNDLE"
+
+
+# we create the hash links for certificate, openssl library need 
+# this link to be able to find a CA certificate
+if { openssl version; } >/dev/null 2>&1; then
+	c_rehash "$CERTSDIR" >/dev/null 2>&1
+
+elif { /opt/csw/bin/openssl version; } >/dev/null 2>&1; then
+	OPENSSL="/opt/csw/bin/openssl" /opt/csw/bin/c_rehash "$CERTSDIR" >/dev/null 2>&1
+
+# openssl binary isn't available, so we fall back our own provided file containing
+# hash value for certificates provided by this package
+# this way, we don't stricly depend on the openssl_utils package
+elif [ -f "$CACERTS_DIR/hash.db" ]; then
+	cd "$CERTSDIR"
+	for FILE in *.pem; do
+		HASH=`awk -F= " \\\$1 == \"$FILE\" { print \\\$2; exit 0 }" "$CACERTS_DIR/hash.db"`
+		if [ -n "$HASH" ]; then
+			ln -s "$FILE" "$HASH"
+		else
+			echo
+			echo "WARNING: a custom certificate was installed, you need to install openssl_utils so" 
+		        echo "         update-ca-certificates is able to generate the hash of your custom certificate."	
 		fi
-		CERTFILE="$CERTSDIR/$CERTFILE"
-	fi
-
-	cd "$ETCCERTSDIR" && ln -sf "$CERTFILE" "`basename $CERTFILE`.pem"
-done
-
-cd "$ETCCERTSDIR" && cat *.pem > "$BUNDLETMP"
-chmod 0644 "$BUNDLETMP"
-mv -f "$BUNDLETMP" "$ETCCERTSDIR/$CERTBUNDLE"
-
-if [ "$verbose" = 0 ]; then
-	OPENSSL=/opt/csw/bin/openssl /opt/csw/bin/c_rehash . >/dev/null 2>&1
-else
-	OPENSSL=/opt/csw/bin/openssl /opt/csw/bin/c_rehash .
+	done
 fi
+	
 echo "done."
