Improving SMF support: o Adding refresh method. Fixing bug with the stop method declaration. o Adding properties for configuring the mpf.conf file and setting --verbose.

diff --git a/csw/trunk/server/mpd/files/svc-cswmpd b/csw/trunk/server/mpd/files/svc-cswmpd
--- a/csw/trunk/server/mpd/files/svc-cswmpd
+++ b/csw/trunk/server/mpd/files/svc-cswmpd
@@ -1,12 +1,64 @@
+#!/bin/sh
+
+set -e
+
+##########################################################
+# SMF Support
+##########################################################
+
+. /lib/svc/share/smf_include.sh
+
+getproparg() {
+  val=`svcprop -p $1 $SMF_FMRI`
+  [ -n "$val" ] && echo $val
+}
+
+##########################################################
+# Get configuration values and set defaults
+##########################################################
+
 PREFIX=/opt/csw
-CONF=/opt/csw/etc/mpd.conf
+CONF=`getproparg mpd/config`
+VERBOSE=`getproparg mpd/verbose`
+
+if [ -z "$CONF" ]
+then
+  CONF=/opt/csw/etc/mpd.conf
+fi
+
+##########################################################
+# Validate
+##########################################################
+
+if [ -z "$SMF_FMRI" ]
+then
+  echo "SMF framework variables are not initialized."
+  exit $SMF_EXIT_ERR
+fi
+
+if [ ! -r $CONF ]
+then
+  echo "Missing configuration file: $CONF"
+  exit $SMF_EXIT_ERR
+fi
+
+if [ "$VERBOSE" = "true" ]
+then
+  VERBOSE="--verbose"
+else
+  VERBOSE=""
+fi
+
+##########################################################
+# Main
+##########################################################
 
 start() {
-  $PREFIX/sbin/mpd $CONF
+  $PREFIX/sbin/mpd $VERBOSE $CONF
 }
 
 stop() {
-  $PREFIX/sbin/mpd --kill $CONF
+  $PREFIX/sbin/mpd $VERBOSE --kill $CONF
 }
 
 case "$1" in
@@ -29,4 +81,4 @@ case "$1" in
   ;;
 esac
 
-exit 0
+exit $SMF_EXIT_OK
