mGAR v2-git: Merging in the v2 branch

diff --git a/csw/mgar/gar/v2-git/bin/checkpkg b/csw/mgar/gar/v2-git/bin/checkpkg
--- a/csw/mgar/gar/v2-git/bin/checkpkg
+++ b/csw/mgar/gar/v2-git/bin/checkpkg
@@ -1,6 +1,13 @@
 #!/bin/ksh -p
-
-# checkpkg 1.50 (diff to 1.46a: check multiple package files)
+# 
+# $Id$
+#
+# checkpkg 1.51
+#
+# diff to 1.46a
+#  - check multiple package files
+#  - checkpkg.d plugin support
+#
 # This script examines a package that has been put together
 # for submittal to the CSW archive at opencsw.org
 #
@@ -16,9 +23,28 @@
 
 
 PATH=$PATH:/usr/sbin
+readonly NAME_MAX_LENGTH=${NAME_MAX_LENGTH:-20}
 
 LOCAL_ARCH=`uname -p`
+if [[ -z "${CHECKPKG_TMPDIR}" ]]; then
+  readonly CHECKPKG_TMPDIR="/var/tmp"
+else
+  readonly CHECKPKG_TMPDIR
+fi
 
+# Colors only when running interactively
+if [[ -t 1 ]]; then
+	GREEN="\\033[0;32;40m"
+	RED="\\033[1;31;40m"
+	COLOR_RESET="\\033[00m"
+else
+	GREEN=""
+	RED=""
+	COLOR_RESET=""
+fi
+
+readonly selfpath="$0"
+readonly selfargs="$*"
 
 # always print out a warning message. (to stderr)
 # exit script, if quit_on_warn set
@@ -28,9 +54,15 @@ cleanup(){
 	if [[ -d "$EXTRACTDIR" ]] ; then
 		rm -rf $EXTRACTDIR
 	fi
-	if [[ "$TMPARCHIVE" != "" ]] ; then
-		[ -f "$TMPARCHIVE" ] && rm $TMPARCHIVE
-	fi
+	cleantmparchives
+}
+
+cleantmparchives() {
+	for TMPARCHIVE in $tmparchives; do
+		if [[ "$TMPARCHIVE" != "" ]]; then
+			[ -f "$TMPARCHIVE" ] && rm $TMPARCHIVE
+		fi
+	done
 }
 
 cleanupset(){
@@ -51,8 +83,39 @@ errmsg(){
 	print ERROR: $* >/dev/fd/2
 	cleanup
 	cleanupset
+	print "To run checkpkg in the debug mode, add the '-d' flag:"
+	print "${selfpath} -d ${selfargs}"
 	exit 1
 }
+
+debugmsg() {
+	if [[ "${DEBUG}" != "" ]]; then
+		print "DEBUG: $*" > /dev/fd/2
+	fi
+}
+
+set_variables_for_individual_package_check() {
+	f=$1
+	file $f \
+	    | sed 's/^[^:]*://' \
+	    | grep gzip >/dev/null
+	if [ $? -eq 0 ] ; then
+		TMPARCHIVE=$CHECKPKG_TMPDIR/`basename $f`
+		if [[ -f $TMPARCHIVE ]] ; then
+			print ERROR: $TMPARCHIVE already exists
+			
+		fi
+		gzcat $f >$TMPARCHIVE || exit 1
+		f=$TMPARCHIVE
+	fi
+	pkgname=`nawk 'NR == 2 {print $1; exit;}' $f`
+	pkgnames="$pkgnames $pkgname"
+}
+
+if [[ "$1" == "-d" ]] ; then
+	DEBUG=1
+	shift
+fi
 
 if [[ "$1" == "-e" ]] ; then
 	quit_on_warn=1;
@@ -65,10 +128,18 @@ if [[ "$1" == "-h" ]] ; then
 fi
 
 # a unique filename for the list of package deps and libs we see in a 'set'
-SETINF=/tmp/checkpkg.$$.`date +%Y%m%d%H%M%S`
+SETINF=$CHECKPKG_TMPDIR/checkpkg.$$.`date +%Y%m%d%H%M%S`
 SETLIBS=$SETINF.libs
 SETDEPS=$SETINF.deps
+pkgnames=""
+tmparchives=""
 
+EXTRACTDIR=$CHECKPKG_TMPDIR/dissect.$$
+
+if [ -d $EXTRACTDIR ] ; then
+	print ERROR: $EXTRACTDIR already exists
+	exit 1
+fi
 
 for f in "$@"
 do
@@ -82,9 +153,6 @@ fi
 
 
 case $f in
-	cswutils-*)
-		:
-	;;
 	*)
 	print Examining $f
 
@@ -111,30 +179,13 @@ case $f in
 	done
 esac
 
-print Extracting files for more detailed inspection...
+print Extracting all files for more detailed inspection...
 
-file $f |sed 's/^.*://' |grep gzip >/dev/null
-if [ $? -eq 0 ] ; then
-	TMPARCHIVE=/tmp/`basename $f`
-	if [[ -f $TMPARCHIVE ]] ; then
-		print ERROR: $TMPARCHIVE already exists
-		
-	fi
-	gzcat $f >$TMPARCHIVE || exit 1
-	f=$TMPARCHIVE
-fi
-
-pkgname=`nawk 'NR == 2 {print $1; exit;}' $f`
-
-EXTRACTDIR=/tmp/dissect.$$
-
-if [ -d $EXTRACTDIR ] ; then
-	print ERROR: $EXTRACTDIR already exists
-	exit 1
-fi
+set_variables_for_individual_package_check "$f"
 
 mkdir $EXTRACTDIR
 
+# FIXME: This doesn't support multiple packages
 TMPFILE=$EXTRACTDIR/pkginfo
 
 
@@ -158,8 +209,7 @@ pkgarch=`sed -n 's/^ARCH=//p' $TMPFILE|head -1`
 
 case $software in
      *[A-Z]*)
-	echo ERROR: $software must be all lowercase
-	exit 1
+	errmsg "$software must be all lowercase"
 	;;
 esac
 
@@ -213,8 +263,8 @@ if [ "$basedir" != "" ] ; then
 	print basedir="'$basedir'"
 fi
 
-if [[ ${#software} -gt 20 ]] ; then errmsg $f: software name greater than 20 chars ; fi
-if [[ ${#pkgname} -gt 20 ]] ; then errmsg $f: pkg name greater than 20 chars; fi
+if [[ ${#software} -gt ${NAME_MAX_LENGTH} ]] ; then errmsg $f: software name greater than 20 chars ; fi
+if [[ ${#pkgname} -gt ${NAME_MAX_LENGTH} ]] ; then errmsg $f: pkg name greater than 20 chars; fi
 
 if [ "$software" = "" ] ; then errmsg $f: software field not set properly in NAME ; fi
 if [ "$pkgname" = "" ] ; then errmsg $f: pkgname field blank ; fi
@@ -228,8 +278,7 @@ if [ "$hotline" = "" ] ; then errmsg $f: HOTLINE field blank ; fi
 
 case $version in
 	*-*)
-		print ERROR: VERSION field not allowed to have '"-"' in it
-		exit 1
+		errmsg "VERSION field not allowed to have \"-\" in it"
 	;;
 	*,REV=20[01][0-9].[0-9][0-9].[0-9][0-9]*)
 		:
@@ -250,6 +299,17 @@ case $pkgarch in
 	print ERROR: non-standard ARCH def in package: $pkgarch
 	rm -rf $EXTRACTDIR $TMPARCHIVE
 	exit 1
+esac
+
+case $f in
+  *${pkgarch}*)
+    print "f: $f, pkgarch: $pkgarch"
+    ;;
+  *)
+    print "The file name is '$f'."
+    print "The pkgarch is '$pkgarch'."
+    errmsg "ERROR: package file name and pkgarch don't match."
+    ;;
 esac
 
 goodarch=yes
@@ -303,7 +363,6 @@ pkgtrans(){
 print ""
 print Extracing pkg for examination of files...
 pkgtrans $f $EXTRACTDIR $pkgname
-
 
 #############################################################
 # We now have the package expanded, in "directory" form, in
@@ -406,7 +465,7 @@ if [[ "$goodarch" = "yes" ]] ; then
 	#cat $EXTRACTDIR/elflist| xargs ldd  2>/dev/null |fgrep  '.so' |
 	#              sed 's:^.*=>[^/]*::' | nawk '{print $1}' |sort -u >$EXTRACTDIR/liblist
 
-		cat $EXTRACTDIR/elflist| xargs dump -Lv |nawk '$2=="NEEDED"{print $3}' |
+		cat $EXTRACTDIR/elflist| xargs /usr/ccs/bin/dump -Lv |nawk '$2=="NEEDED"{print $3}' |
 			sort -u | egrep -v $EXTRACTDIR >$EXTRACTDIR/liblist
 
 			
@@ -439,17 +498,15 @@ fi
 # sanity check against "depends on self"
 nawk '$2=="'$pkgname'" {exit 1}' $EXTRACTDIR/$pkgname/install/depend
 if [[ $? -ne 0 ]] ; then
-	print ERROR: $pkgname references self in depend file
-	exit 1
+	errmsg "$pkgname references self in depend file"
 fi
 
-# Verify that there are no double depends
+# Verify that there are no multiple depends
 repeated_depends="$(awk '{print $2}' $EXTRACTDIR/$pkgname/install/depend \
   | sort | uniq -c | awk '{print $1}' | sort | uniq | wc -l)"
 if [[ "$repeated_depends" -gt 1 ]]; then
         cat $EXTRACTDIR/$pkgname/install/depend
-        print ERROR: $pkgname has double depends
-        exit 1
+        errmsg "$pkgname has multiple depends"
 fi
 
 #to retain a record of all packages currently being examined from $@
@@ -474,47 +531,6 @@ do
     fi
 done
 
-egrep -v 'SUNWbcp|SUNWowbcp|SUNWucb' /var/sadm/install/contents |
-		fgrep -f $EXTRACTDIR/liblist >$EXTRACTDIR/shortcatalog
-
-
-
-for lib in `cat $EXTRACTDIR/liblist` ; do
-	grep "[/=]$lib[ =]" $EXTRACTDIR/$pkgname/pkgmap
-	if [[ $? -eq 0 ]] ; then
-		echo $lib provided by package itself
-		continue
-	else
-	    grep "[/=]$lib[ =]" $SETLIBS
-	    if [[ $? -eq 0 ]]; then
-		echo "$lib provided by package set being evaluated."
-		continue
-	    fi
-	fi
-
-	libpkg=`grep /$lib $EXTRACTDIR/shortcatalog |
-	      sed 's/^.* \([^ ]*\)$/\1/' |sort -u`
-
-	if [[ -z "$libpkg" ]] ; then
-		echo "$lib $pkgname" >> $SETLIBS.missing
-		print Cannot find package providing $lib.  Storing for delayed validation.
-	else
-		print $libpkg | fmt -1 >>$EXTRACTDIR/libpkgs
-	fi
-done
-
-sort -u $EXTRACTDIR/libpkgs >$EXTRACTDIR/libpkgs.x
-mv $EXTRACTDIR/libpkgs.x $EXTRACTDIR/libpkgs
-
-diff $EXTRACTDIR/deppkgs $EXTRACTDIR/libpkgs >/dev/null
-if [[ $? -ne 0 ]] ; then
-	print SUGGESTION: you may want to add some or all of the following as depends:
-	print '   (Feel free to ignore SUNW or SPRO packages)'
-	diff $EXTRACTDIR/deppkgs $EXTRACTDIR/libpkgs | fgrep '>'
-fi
-
-
-
 if [[ "$basedir" != "" ]] ; then
 	print
 	if [[ -f $EXTRACTDIR/elflist ]] ; then
@@ -530,12 +546,89 @@ if [[ "$basedir" != "" ]] ; then
 	fi
 fi
 
+# Plugin section.
+#
+# Plugins should live in checkpkg.d subdirectory in the same directory in which
+# checkpkg is.  Each plugin file name should be an executable and begin with
+# "checkpkg-".
 
-cleanup
+tmparchives="$tmparchives $TMPARCHIVE"
+done
+
+# All packages have been extracted.
+
+set_variables_for_individual_package_check "$f"
+
+test_suite_ok=1
+checkpkg_scriptname=`basename $0`
+checkpkg_basedir=${0%/${checkpkg_scriptname}}
+plugindir=${checkpkg_basedir}/checkpkg.d
+
+# Cleaning up old *.pyc files which can cause grief.  This is because of the
+# move of Python libraries.
+for pyc_file in ${plugindir}/opencsw.pyc \
+                ${plugindir}/checkpkg.pyc; do
+  if [ -f "${pyc_file}" ]; then
+    echo "Removing old pyc file: '${pyc_file}'"
+    rm "${pyc_file}"
+  fi
+done
+
+# /var/sadm/install/contents cache update
+${plugindir}/update_contents_cache.py
+
+if [[ "${DEBUG}" != "" ]]; then
+	extra_options="--debug"
+fi
+debugmsg "plugindir: '$plugindir'"
+log_files=""
+if [[ -d "$plugindir" ]]; then
+  echo "Running modular tests"
+	# echo plugin dir exists
+	for plugin in "${plugindir}"/checkpkg-*; do
+		if [[ -x "${plugin}" ]]; then
+			debugmsg "Executing: ${plugin} $extra_options -e \"${EXTRACTDIR}\" ${pkgnames}"
+			plugin_base_name=`basename ${plugin}`
+			plugin_log="${EXTRACTDIR}/${plugin_base_name}.log"
+			log_files="${log_files} ${plugin_log}"
+			printf "TEST: ${plugin} running..."
+			${plugin} $extra_options -e "${EXTRACTDIR}" ${pkgnames} > "${plugin_log}" 2>&1
+			if [[ "$?" -ne 0 ]]; then
+				printf "\rTEST: ${plugin} ${RED}[FAIL]${COLOR_RESET}        \\n"
+				test_suite_ok=0
+			else
+				printf "\rTEST: ${plugin} ${GREEN}[OK]${COLOR_RESET}        \\n"
+			fi
+		else
+			debugmsg "'${plugin}' is not executable"
+		fi
+	done
+else
+	debugmsg "plugin dir does not exist"
+fi
+
+echo
+for log_file in ${log_files}; do
+	if [[ -s "${log_file}" ]]; then
+		debugmsg ">> LOG START: ${log_file}"
+		cat "${log_file}"
+		debugmsg "<< LOG END: ${log_file}"
+  else
+  	debugmsg "-- LOG ${log_file} is empty"
+	fi
+done
+echo
+
+if [[ ${test_suite_ok} -ne 1 ]]; then
+	errmsg "One or more modular tests have failed."
+else
+	print "All modular tests were successful."
+fi
 
 print ""
 
-done
+# Cleaning up after all packages
+cleanup
 
 if [ -s $SETDEPS.missing ]; then
     print "Doing late evaluations of package dependencies."
@@ -549,21 +642,6 @@ if [ -s $SETDEPS.missing ]; then
 	    print "Validated $dep as a dependency for $pkg."
 	fi
     done < $SETDEPS.missing
-fi
-
-if [ -s $SETLIBS.missing ]; then
-    print "Doing late evaluations of package library dependencies."
-    while read ldep; do
-	lib=`echo $ldep | nawk '{print $1}'`
-        [ "$lib" = "libm.so.2" ] && continue
-	pkg=`echo $ldep | nawk '{print $2}'`
-	/usr/bin/grep "[/=]$lib[ =]" $SETLIBS >/dev/null
-	if [ $? -ne 0 ]; then
-	    errmsg "Couldn't find a package providing $lib"
-	else
-	    print "A package in the set being evaluated provides $lib"
-	fi
-    done < $SETLIBS.missing
 fi
 
 cleanupset
