mGAR v2-git: Merged changes from the v2 branch.

diff --git a/csw/mgar/gar/v2-git/bin/checkpkg b/csw/mgar/gar/v2-git/bin/checkpkg
--- a/csw/mgar/gar/v2-git/bin/checkpkg
+++ b/csw/mgar/gar/v2-git/bin/checkpkg
@@ -21,9 +21,14 @@
 # you know you are tracking the most current version.
 # 
 
-
 PATH=$PATH:/usr/sbin
 readonly NAME_MAX_LENGTH=${NAME_MAX_LENGTH:-20}
+
+command_basename=`basename $0`
+command_basedir="${0%/${command_basename}}"
+libshdir="${command_basedir}/../lib/sh"
+readonly command_basename command_basedir libshdir
+. "${libshdir}/libcheckpkg.sh"
 
 LOCAL_ARCH=`uname -p`
 if [[ -z "${CHECKPKG_TMPDIR}" ]]; then
@@ -36,15 +41,18 @@ fi
 if [[ -t 1 ]]; then
 	GREEN="\\033[0;32;40m"
 	RED="\\033[1;31;40m"
+	BOLD="\\033[1m"
 	COLOR_RESET="\\033[00m"
 else
 	GREEN=""
 	RED=""
+	BOLD=""
 	COLOR_RESET=""
 fi
+readonly GREEN RED BOLD COLOR_RESET
 
 readonly selfpath="$0"
-readonly selfargs="$*"
+readonly selfargs="$@"
 
 # always print out a warning message. (to stderr)
 # exit script, if quit_on_warn set
@@ -122,8 +130,9 @@ if [[ "$1" == "-e" ]] ; then
 	shift
 fi
 if [[ "$1" == "-h" ]] ; then
-	print 'Usage: checkpkg [-e] pkg1 [pkg2 ....]'
-	print '   -e = "exit on warnings"'
+	print 'Usage: checkpkg [-d] [-e] pkg1 [pkg2 ....]'
+	print '   -d  display debug messages'
+	print '   -e  exit on warnings (soon to be obsolete)'
 	shift
 fi
 
@@ -207,12 +216,6 @@ hotline=`sed -n 's/^HOTLINE=//p' $TMPFILE`
 basedir=`sed -n 's/^BASEDIR=//p' $TMPFILE`
 pkgarch=`sed -n 's/^ARCH=//p' $TMPFILE|head -1`
 
-case $software in
-     *[A-Z]*)
-	errmsg "$software must be all lowercase"
-	;;
-esac
-
 case `basename $f` in
 	${software}-${version}-*)
 		# file name looks okay
@@ -263,8 +266,12 @@ if [ "$basedir" != "" ] ; then
 	print basedir="'$basedir'"
 fi
 
-if [[ ${#software} -gt ${NAME_MAX_LENGTH} ]] ; then errmsg $f: software name greater than 20 chars ; fi
-if [[ ${#pkgname} -gt ${NAME_MAX_LENGTH} ]] ; then errmsg $f: pkg name greater than 20 chars; fi
+if [[ ${#software} -gt ${NAME_MAX_LENGTH} ]] ; then
+	errmsg "$f: software name longer than ${NAME_MAX_LENGTH} chars"
+fi
+if [[ ${#pkgname} -gt ${NAME_MAX_LENGTH} ]] ; then
+	errmsg "$f: pkg name longer than ${NAME_MAX_LENGTH} chars"
+fi
 
 if [ "$software" = "" ] ; then errmsg $f: software field not set properly in NAME ; fi
 if [ "$pkgname" = "" ] ; then errmsg $f: pkgname field blank ; fi
@@ -331,38 +338,9 @@ esac
 #	exit 0
 #fi
 
-
-# This function exists, because pkgtrans is BROKEN!!
-# It leaves a directory in /var/tmp/aaXXXXXXX, even after clean quit
-# SO, emulate pkgtrans behaviour, for "pkgtrans src destdir pkgname"
-#   Except that we ignore pkgname arg, and just do first one we find.
-#  and we are a bit hacky about how we do things.
-pkgtrans(){
-	if [[ ! -d $2 ]] ; then
-		print ERROR: $2 is not a directory >/dev/fd/2
-		return 1
-	fi
-	hdrblks=`(dd if=$1 skip=1 2>/dev/null| cpio -i -t  >/dev/null) 2>&1 |
-		nawk '{print $1; exit;}'`
-
-	## print initial hdrblks=$hdrblks
-
-	hdrblks=$(($hdrblks + 1))
-	mkdir $2/$3 || return 1
-
-	dd if=$1 skip=$hdrblks 2>/dev/null | (cd $2/$3 ; cpio -ivdm)
-	# on fail, SOMETIMES cpio returns 1, but sometimes it returns 0!!
-	if [[ ! -d $2/$3/install ]] ; then
-		print retrying extract with different archive offset...
-		# no, I cant tell in advance why/when the prev fails
-		hdrblks=$(($hdrblks + 1))
-		dd if=$1 skip=$hdrblks 2>/dev/null| (cd $2/$3 ; cpio -ivdm)
-	fi
-}
-
 print ""
 print Extracing pkg for examination of files...
-pkgtrans $f $EXTRACTDIR $pkgname
+custom_pkgtrans $f $EXTRACTDIR $pkgname
 
 #############################################################
 # We now have the package expanded, in "directory" form, in
@@ -506,7 +484,7 @@ repeated_depends="$(awk '{print $2}' $EXTRACTDIR/$pkgname/install/depend \
   | sort | uniq -c | awk '{print $1}' | sort | uniq | wc -l)"
 if [[ "$repeated_depends" -gt 1 ]]; then
         cat $EXTRACTDIR/$pkgname/install/depend
-        errmsg "$pkgname has multiple depends"
+        errmsg "$pkgname lists a dependency more than once, see above"
 fi
 
 #to retain a record of all packages currently being examined from $@
@@ -520,8 +498,8 @@ do
     if [[ $? -ne 0 ]]; then
 	#if we've already looked at the package named $dep,
 	#it'll be in the file.
- 	awk "\$1 == \"$dep\" {print}" $SETDEPS | /usr/bin/grep $dep >/dev/null
- 	if [[ $? -ne 0 ]]; then #we haven't yet seen this package in our set
+	awk "\$1 == \"$dep\" {print}" $SETDEPS | /usr/bin/grep $dep >/dev/null
+	if [[ $? -ne 0 ]]; then #we haven't yet seen this package in our set
 	    echo "Can't validate dependence on $dep.  Storing for delayed validation."
 	    #store for validation at the end.
 	    echo "$dep $pkgname" >> $SETDEPS.missing
@@ -560,69 +538,103 @@ done
 set_variables_for_individual_package_check "$f"
 
 test_suite_ok=1
-checkpkg_scriptname=`basename $0`
-checkpkg_basedir=${0%/${checkpkg_scriptname}}
-plugindir=${checkpkg_basedir}/checkpkg.d
+checkpkg_module_dir=${command_basedir}/checkpkg.d
+checkpkg_module_tag="checkpkg-"
+checkpkg_stats_basedir="${HOME}/.checkpkg/stats"
 
 # Cleaning up old *.pyc files which can cause grief.  This is because of the
 # move of Python libraries.
-for pyc_file in ${plugindir}/opencsw.pyc \
-                ${plugindir}/checkpkg.pyc; do
+for pyc_file in ${checkpkg_module_dir}/opencsw.pyc \
+                ${checkpkg_module_dir}/checkpkg.pyc; do
   if [ -f "${pyc_file}" ]; then
     echo "Removing old pyc file: '${pyc_file}'"
     rm "${pyc_file}"
   fi
 done
 
-# /var/sadm/install/contents cache update
-${plugindir}/update_contents_cache.py
-
 if [[ "${DEBUG}" != "" ]]; then
 	extra_options="--debug"
 fi
-debugmsg "plugindir: '$plugindir'"
+
+# /var/sadm/install/contents cache update
+${command_basedir}/update_contents_cache.py
+# Collects package stats to be later analyzed
+${command_basedir}/checkpkg_collect_stats.py ${extra_options} "$@"
+
+debugmsg "checkpkg_module_dir: '$checkpkg_module_dir'"
 log_files=""
-if [[ -d "$plugindir" ]]; then
-  echo "Running modular tests"
-	# echo plugin dir exists
-	for plugin in "${plugindir}"/checkpkg-*; do
+module_name_format="%-40s"
+md5sums=`gmd5sum "$@" | awk '{print $1}'`
+if [[ -d "${checkpkg_module_dir}" ]]; then
+	echo "Running modular tests in ${checkpkg_module_dir}"
+	for plugin in "${checkpkg_module_dir}/${checkpkg_module_tag}"*; do
 		if [[ -x "${plugin}" ]]; then
-			debugmsg "Executing: ${plugin} $extra_options -e \"${EXTRACTDIR}\" ${pkgnames}"
 			plugin_base_name=`basename ${plugin}`
 			plugin_log="${EXTRACTDIR}/${plugin_base_name}.log"
 			log_files="${log_files} ${plugin_log}"
-			printf "TEST: ${plugin} running..."
-			${plugin} $extra_options -e "${EXTRACTDIR}" ${pkgnames} > "${plugin_log}" 2>&1
+			plugin_name="`echo ${plugin} | sed -e 's+.*/checkpkg-++' | sed -e 's+\.py$++'`"
+			error_tag_file="tags.${plugin_name}"
+			printf "${BOLD}${module_name_format}${COLOR_RESET} running..." "${plugin_name}"
+			debugmsg "Executing: ${plugin} $extra_options -b \"${checkpkg_stats_basedir}\" -o \"${EXTRACTDIR}/${error_tag_file}\" ${md5sums}"
+			${plugin} \
+				$extra_options \
+				-b "${checkpkg_stats_basedir}" \
+				-o "${EXTRACTDIR}/${error_tag_file}" \
+				${md5sums} \
+				> "${plugin_log}" 2>&1
 			if [[ "$?" -ne 0 ]]; then
-				printf "\rTEST: ${plugin} ${RED}[FAIL]${COLOR_RESET}        \\n"
+				printf "\r${module_name_format} ${RED}[ERROR]${COLOR_RESET}        \\n" "${plugin_name}"
 				test_suite_ok=0
 			else
-				printf "\rTEST: ${plugin} ${GREEN}[OK]${COLOR_RESET}        \\n"
+				printf "\r${module_name_format} [Done]        \\n" "${plugin_name}"
 			fi
 		else
 			debugmsg "'${plugin}' is not executable"
 		fi
 	done
 else
-	debugmsg "plugin dir does not exist"
+	debugmsg "module dir ${checkpkg_module_dir} does not exist"
 fi
 
-echo
 for log_file in ${log_files}; do
-	if [[ -s "${log_file}" ]]; then
+	if [[ `gwc -c "${log_file}" | awk '{print $1}'` -gt 1 ]]; then
 		debugmsg ">> LOG START: ${log_file}"
 		cat "${log_file}"
 		debugmsg "<< LOG END: ${log_file}"
-  else
-  	debugmsg "-- LOG ${log_file} is empty"
+	else
+		debugmsg "-- LOG ${log_file} is empty"
 	fi
 done
-echo
 
 if [[ ${test_suite_ok} -ne 1 ]]; then
-	errmsg "One or more modular tests have failed."
+	errmsg "One or more modular tests have finished with an error."
 else
-	print "All modular tests were successful."
+	print "All modular tests completed.  Analyzing the reports."
+fi
+
+if [[ "${DEBUG}" != "" ]]; then
+	override_info_printed=0
+	for tagfile in ${EXTRACTDIR}/tags.*; do
+		if [[ -s "${tagfile}" ]]; then
+			if [[ "${override_info_printed}" -ne 1 ]]; then
+				echo "# You can use the following lines to create overrides"
+				echo "# See http://wiki.opencsw.org/checkpkg"
+				override_info_printed=1
+			fi
+			echo "# ${tagfile}:"
+			cat "${tagfile}"
+		fi
+	done
+fi
+
+# Collecting errors and applying the overrides.
+${command_basedir}/analyze_module_results.py \
+	-e "${EXTRACTDIR}" \
+	${pkgnames}
+if [[ "$?" -ne 0 ]]; then
+	errmsg "${RED}Modular checks are reporting errors.${COLOR_RESET}"
+else
+	print "${GREEN}All modular tests were successful.${COLOR_RESET}"
 fi
 
 print ""
