icinga/trunk: update to 1.7.1

diff --git a/csw/mgar/pkg/icinga/trunk/files/cswicinga b/csw/mgar/pkg/icinga/trunk/files/cswicinga
--- a/csw/mgar/pkg/icinga/trunk/files/cswicinga
+++ b/csw/mgar/pkg/icinga/trunk/files/cswicinga
@@ -1,53 +1,86 @@
 #!/bin/sh
-# 
+#
 # chkconfig: 345 99 01
 # description: Icinga network monitor
 #
-# File : icinga
+# Modified for OpenCSW and Solaris by Juergen Arndt
 #
-# Author : Jorge Sanchez Aymar (jsanchez@lanchile.cl)
-# 
-# Changelog :
-#
-# 1999-07-09 Karl DeBisschop <kdebisschop@infoplease.com>
-#  - setup for autoconf
-#  - add reload function
-# 1999-08-06 Ethan Galstad <egalstad@nagios.org>
-#  - Added configuration info for use with RedHat's chkconfig tool
-#    per Fran Boon's suggestion
-# 1999-08-13 Jim Popovitch <jimpop@rocketship.com>
-#  - added variable for icinga/var directory
-#  - cd into icinga/var directory before creating tmp files on startup
-# 1999-08-16 Ethan Galstad <egalstad@nagios.org>
-#  - Added test for rc.d directory as suggested by Karl DeBisschop
-# 2000-07-23 Karl DeBisschop <kdebisschop@users.sourceforge.net>
-#  - Clean out redhat macros and other dependencies
-# 2003-01-11 Ethan Galstad <egalstad@nagios.org>
-#  - Updated su syntax (Gary Miller)
-#
-# Description: Starts and stops the Icinga monitor
-#              used to provide network services status.
-#
-# Modified for OpenCSW by Juergen Arndt, 2009-05-22
-#
+### BEGIN INIT INFO
+# Provides:          icinga
+# Required-Start:    $local_fs $remote_fs $syslog $named $network $time
+# Required-Stop:     $local_fs $remote_fs $syslog $named $network
+# Should-Start:
+# Should-Stop:
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: start and stop Icinga monitoring daemon
+# Description:       Icinga is a service monitoring system
+### END INIT INFO
 
-#FMRI application       # FMRI path for service, see http://wiki.opencsw.org/cswclassutils-package#toc0
+## definitions ##
+prefix=/opt/csw/icinga
+exec_prefix=/opt/csw/icinga
+IcingaBin=/opt/csw/icinga/bin/icinga
+IcingaCfgFile=/etc/opt/csw/icinga/icinga.cfg
+IcingaCommandFile=/var/opt/csw/icinga/rw/icinga.cmd
+IcingaRunFile=/var/opt/csw/icinga/icinga.lock
+IcingaLockDir=/var/lock/subsys
+IcingaLockFile=icinga
+IcingaUser=icinga
+IcingaGroup=icinga
+IcingaChkFile=/var/opt/csw/icinga/icinga.chk
+
+# load extra environment variables
+if [ -f /etc/sysconfig/icinga ]; then
+        . /etc/sysconfig/icinga
+fi
+
+# For Solaris
+
+SOLREL=`uname -r | awk -F. '{print $2}'`
+
+if [ -f /lib/svc/share/smf_include.sh ]
+then
+	. /lib/svc/share/smf_include.sh
+fi
+
+# Source function library
+# Solaris doesn't have an rc.d directory, so do a test first
+if [ -f /etc/rc.d/init.d/functions ]; then
+        . /etc/rc.d/init.d/functions
+elif [ -f /etc/init.d/functions ]; then
+        . /etc/init.d/functions
+fi
+
+# Check that icinga exists.
+if [ ! -f $IcingaBin ]; then
+    echo "Executable file $IcingaBin not found.  Exiting."
+    exit 1
+fi
+
+# Check that icinga.cfg exists.
+if [ ! -f $IcingaCfgFile ]; then
+    echo "Configuration file $IcingaCfgFile not found.  Exiting."
+
+	if [ $SOLREL -lt 10 ]
+	then
+		exit 1
+	else
+		exit $SMF_EXIT_ERR_CONFIG
+	fi
+
+fi
+
+
+## helper functions ##
 
 status_icinga ()
 {
 
-	if test -x $IcingaCGI/daemonchk.cgi; then
-		if $IcingaCGI/daemonchk.cgi -l $IcingaRunFile; then
-		        return 0
-		else
-			return 1
-		fi
+	if ps -p $IcingaPID > /dev/null 2>&1; then
+	        return 0
 	else
-		if ps -p $IcingaPID > /dev/null 2>&1; then
-		        return 0
-		else
-			return 1
-		fi
+		return 1
 	fi
 
 	return 1
@@ -67,17 +100,21 @@ printstatus_icinga()
 
 killproc_icinga ()
 {
-
-	kill $2 $IcingaPID
-
+	if kill -0  $IcingaPID  >/dev/null 2>&1; then
+		kill $2 $IcingaPID
+	fi
 }
 
+kill9proc_icinga()
+{
+	kill -9 $IcingaPID
+}
 
 pid_icinga ()
 {
 
 	if test ! -f $IcingaRunFile; then
-		echo "No lock file found in $IcingaRunFile"
+		echo "Icinga not running. No lock file found in $IcingaRunFile"
 		exit 1
 	fi
 
@@ -85,65 +122,62 @@ pid_icinga ()
 }
 
 
-# Source function library
-# Solaris doesn't have an rc.d directory, so do a test first
-if [ -f /etc/rc.d/init.d/functions ]; then
-	. /etc/rc.d/init.d/functions
-elif [ -f /etc/init.d/functions ]; then
-	. /etc/init.d/functions
-fi
+chk_config ()
+{
+	printf "Running configuration check..."
+	$IcingaBin -v $IcingaCfgFile > $IcingaChkFile 2>&1
+	if test $? -ne 0; then
+		if test -z "$1"; then
+			cat $IcingaChkFile
+			echo "Result saved to $IcingaChkFile"
+		else
+			echo $1
+		fi
+		exit 1
+	fi
+	rm -f $IcingaChkFile
+	echo "OK"
+	#exit 0
+}
 
-prefix=/opt/csw/icinga
-exec_prefix=/opt/csw/icinga
-IcingaBin=/opt/csw/icinga/bin/icinga
-IcingaCfgFile=/opt/csw/icinga/etc/icinga.cfg
-IcingaStatusFile=/opt/csw/icinga/var/status.dat
-IcingaRetentionFile=/opt/csw/icinga/var/retention.dat
-IcingaCommandFile=/opt/csw/icinga/var/rw/icinga.cmd
-IcingaVarDir=/opt/csw/icinga/var
-IcingaRunFile=/var/opt/csw/icinga/icinga.lock
-IcingaLockDir=/var/lock/subsys
-IcingaLockFile=icinga
-IcingaCGIDir=/opt/csw/icinga/sbin
-IcingaUser=icinga
-IcingaGroup=icinga
-          
+start(){
+	# Check if icinga is already running
+	$0 status > /dev/null
+	if [ $? -eq 0 ]; then
+		pid_icinga
+		# check if pid can be found running
+		if status_icinga > /dev/null; then
+			echo "Icinga is already running. PID: $IcingaPID"
+				exit 1
+			else
+				echo "Icinga PID $IcingaPID not running. Removing lockfile."
+				rm -f $IcingaRunFile $IcingaLockDir/$IcingaLockFile
+		fi
+	fi
 
-# Check that icinga exists.
-if [ ! -f $IcingaBin ]; then
-    echo "Executable file $IcingaBin not found.  Exiting."
-    exit 1
-fi
+	printf "Starting icinga: "
+	rm -f $IcingaCommandFile
+	touch $IcingaRunFile
+	chown $IcingaUser:$IcingaGroup $IcingaRunFile
+	$IcingaBin -d $IcingaCfgFile
+	if [ -d $IcingaLockDir ]; then touch $IcingaLockDir/$IcingaLockFile; fi
+	echo "Starting icinga done."
+	exit 0
 
-# Check that icinga.cfg exists.
-if [ ! -f $IcingaCfgFile ]; then
-    echo "Configuration file $IcingaCfgFile not found.  Exiting."
-    exit 1
-fi
-          
+}
+
+
+## MAIN ##
 # See how we were called.
 case "$1" in
 
 	start)
-		echo -n "Starting icinga:"
-		$IcingaBin -v $IcingaCfgFile > /dev/null 2>&1;
-		if [ $? -eq 0 ]; then
-			su - $IcingaUser -c "touch $IcingaVarDir/icinga.log $IcingaRetentionFile"
-			rm -f $IcingaCommandFile
-			touch $IcingaRunFile
-			chown $IcingaUser:$IcingaGroup $IcingaRunFile
-			$IcingaBin -d $IcingaCfgFile
-			if [ -d $IcingaLockDir ]; then touch $IcingaLockDir/$IcingaLockFile; fi
-			echo " done."
-			exit 0
-		else
-			echo "CONFIG ERROR!  Start aborted.  Check your Icinga configuration."
-			exit 1
-		fi
+		chk_config "CONFIG ERROR!  Start aborted. See $IcingaChkFile for details."
+		start
 		;;
 
 	stop)
-		echo -n "Stopping icinga: "
+		printf "Stopping icinga: "
 
 		pid_icinga
 		killproc_icinga icinga
@@ -153,10 +187,10 @@ case "$1" in
  		# happen, and then the exiting icinga will remove the
  		# new IcingaRunFile, allowing multiple icinga daemons
  		# to (sooner or later) run - John Sellens
-		#echo -n 'Waiting for icinga to exit .'
- 		for i in 1 2 3 4 5 6 7 8 9 10 ; do
+		#printf 'Waiting for icinga to exit .'
+ 		for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
  		    if status_icinga > /dev/null; then
- 			echo -n '.'
+ 			printf '.'
  			sleep 1
  		    else
  			break
@@ -164,12 +198,13 @@ case "$1" in
  		done
  		if status_icinga > /dev/null; then
  		    echo ''
- 		    echo 'Warning - icinga did not exit in a timely manner'
+ 		    echo 'Warning - icinga did not exit in a timely manner. Sending kill -9'
+		    kill9proc_icinga
  		else
- 		    echo 'done.'
+ 		    echo 'Stopping icinga done.'
+                    rm -f $IcingaRunFile $IcingaLockDir/$IcingaLockFile
  		fi
 
-		rm -f $IcingaStatusFile $IcingaRunFile $IcingaLockDir/$IcingaLockFile $IcingaCommandFile
 		;;
 
 	status)
@@ -178,58 +213,41 @@ case "$1" in
 		;;
 
 	checkconfig)
-		printf "Running configuration check..."
-		$IcingaBin -v $IcingaCfgFile > /dev/null 2>&1;
-		if [ $? -eq 0 ]; then
-			echo " OK."
-		else
-			echo " CONFIG ERROR!  Check your Icinga configuration."
-			exit 1
-		fi
+		chk_config " CONFIG ERROR!  See $IcingaChkFile for details."
+		;;
+
+	show-errors)
+		chk_config
 		;;
 
 	restart)
-		printf "Running configuration check..."
-		$IcingaBin -v $IcingaCfgFile > /dev/null 2>&1;
-		if [ $? -eq 0 ]; then
-			echo "done."
-			$0 stop
-			$0 start
-		else
-			echo " CONFIG ERROR!  Restart aborted.  Check your Icinga configuration."
-			exit 1
-		fi
+		chk_config " CONFIG ERROR!  Restart aborted.  See $IcingaChkFile for details."
+		$0 stop
+		start
 		;;
 
 	reload|force-reload)
-		printf "Running configuration check..."
-		$IcingaBin -v $IcingaCfgFile > /dev/null 2>&1;
-		if [ $? -eq 0 ]; then
-			echo "done."
-			if test ! -f $IcingaRunFile; then
-				$0 start
-			else
-				pid_icinga
-				if status_icinga > /dev/null; then
-					printf "Reloading icinga configuration..."
-					killproc_icinga icinga -HUP
-					echo "done"
-				else
-					$0 stop
-					$0 start
-				fi
-			fi
+		chk_config " CONFIG ERROR!  Reload aborted.  See $IcingaChkFile for details."
+		if test ! -f $IcingaRunFile; then
+			$0 start
 		else
-			echo " CONFIG ERROR!  Reload aborted.  Check your Icinga configuration."
-			exit 1
+			pid_icinga
+			if status_icinga > /dev/null; then
+				printf "Reloading icinga configuration..."
+				killproc_icinga icinga -HUP
+				echo "done"
+			else
+				$0 stop
+				$0 start
+			fi
 		fi
 		;;
 
 	*)
-		echo "Usage: icinga {start|stop|restart|reload|force-reload|status|checkconfig}"
+		echo "Usage: icinga {start|stop|restart|reload|force-reload|status|checkconfig|show-errors}"
 		exit 1
 		;;
 
 esac
-  
+
 # End of this script
